# Generated by Django 3.2.17 on 2023-02-15 19:10

from django.db import migrations, models
import employeeapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=employeeapi.models.nameFile),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='img', max_length=100),
            preserve_default=False,
        ),
    ]
