# Generated by Django 3.2.17 on 2023-02-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0003_remove_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='defaultImage', max_length=100),
            preserve_default=False,
        ),
    ]
