# Generated by Django 3.2.17 on 2023-02-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0005_remove_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='test',
            field=models.IntegerField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
