# Generated by Django 3.2.17 on 2023-02-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0006_employee_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='test',
        ),
    ]
