# Generated by Django 3.2.17 on 2023-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0007_remove_employee_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=25),
        ),
    ]
