# Generated by Django 3.2.17 on 2023-02-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0011_alter_employee_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='random_number',
            field=models.SlugField(default='asfhiohasdfj', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=10),
        ),
    ]
